apiVersion: apps/v1
kind: Deployment
metadata:
  name: sockpuppet
  namespace: __NAMESPACE__
  labels:
    app: sockpuppet
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sockpuppet
  template:
    metadata:
      labels:
        app: sockpuppet
    spec:
      containers:
      - name: sockpuppet
        image: docker.io/dgtlmoon/sockpuppetbrowser:latest
        ports:
        - containerPort: 3000
      resources:
        requests:
          memory: "512Mi"
        limits:
          memory: "2Gi"
        env:
        - name: DEFAULT_LAUNCH_ARGS
          value: '["--window-size=1920,1080"]'
        - name: SCREEN_WIDTH
          value: '1920'
        - name: SCREEN_HEIGHT
          value: '1080'
        - name: SCREEN_DEPTH
          value: '16'
        - name: MAX_CONCURRENT_CHROME_PROCESSES
          value: '10'
        volumeMounts:
        - name: dshm
          mountPath: /dev/shm
      volumes:
      - name: dshm
        emptyDir:
          medium: Memory

