apiVersion: batch/v1
kind: CronJob
metadata:
  name: changedetection-backup
  namespace: __NAMESPACE__

spec:
  schedule: "0 2 * * *" # Run daily at 2 AM
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: backup-serviceaccount
          initContainers:
          - name: fix-permissions
            image: busybox
            command: ["sh", "-c", "chmod -R 777 /source"]
            volumeMounts:
            - name: pvc-source
              mountPath: /source
          containers:
          - name: backup
            image: bitnami/kubectl:latest
            command:
              - /bin/sh
              - -c
              - |
                sleep 5 && kubectl scale deployment changedetection-io --replicas=0 -n __NAMESPACE__ &&
                sleep 15 && tar -czf /data/backup/changedetection-$(date +'%Y-%m-%d_%H-%M').tar.gz -C /data/source/* . &&
                ls -l /data/backup/changedetection-*.tar.gz &&
                find /data/backup -type f -name "*.tar.gz" -mtime +14 -exec rm -v {} + &&
                kubectl scale deployment changedetection-io --replicas=1 -n __NAMESPACE__
            volumeMounts:
            - name: pvc-source
              mountPath: /data/source
            - name: pvc-backup
              mountPath: /data/backup
          restartPolicy: OnFailure
          volumes:
          - name: pvc-source
            persistentVolumeClaim:
              claimName: changedetection-io
          - name: pvc-backup
            persistentVolumeClaim:
              claimName: backup-pvc

